CREATE TABLE IF NOT EXISTS "entity" (
	"id" text PRIMARY KEY NOT NULL,
	"project" text NOT NULL,
	"isPlayerCharacter" boolean NOT NULL,
	"isNonPlayerCharacter" boolean NOT NULL,
	"isMonster" boolean NOT NULL,
	"isCustom" boolean NOT NULL,
	"name" text NOT NULL,
	"description" text NOT NULL,
	"strength" integer NOT NULL,
	"dexterity" integer NOT NULL,
	"constitution" integer NOT NULL,
	"intelligence" integer NOT NULL,
	"wisdom" integer NOT NULL,
	"charisma" integer NOT NULL,
	"armorClass" integer NOT NULL,
	"hitPoints" integer NOT NULL,
	"temporaryHitPoints" integer,
	"speed" integer NOT NULL,
	"walkingSpeed" integer,
	"flyingSpeed" integer,
	"swimmingSpeed" integer,
	"climbingSpeed" integer,
	"burrowingSpeed" integer,
	"initiative" text NOT NULL,
	"attackBonus" text NOT NULL,
	"damageRolls" text NOT NULL,
	"savingThrows" text NOT NULL,
	"hitDice" text NOT NULL,
	"damageResistances" text,
	"damageImmunities" text,
	"damageVulnerabilities" text,
	"conditionImmunities" text,
	"passivePerception" integer NOT NULL,
	"visionTypes" text NOT NULL,
	"acrobatics" integer,
	"animalHandling" integer,
	"arcana" integer,
	"athletics" integer,
	"deception" integer,
	"history" integer,
	"insight" integer,
	"intimidation" integer,
	"investigation" integer,
	"medicine" integer,
	"nature" integer,
	"perception" integer,
	"performance" integer,
	"persuasion" integer,
	"religion" integer,
	"sleightOfHand" integer,
	"stealth" integer,
	"survival" integer,
	"traitsAndFeatures" text NOT NULL,
	"innateTraits" text,
	"classFeatures" text,
	"legendaryActions" text,
	"lairActions" text,
	"regionalEffects" text,
	"racialTraits" text,
	"backgroundFeatures" text,
	"spellcastingAndMagic" text,
	"spellSaveDC" integer,
	"spellAttackBonus" integer,
	"spellSlots" integer,
	"preparedKnownSpells" text,
	"spellLevel" text,
	"magicalResistances" text,
	"innateSpellcasting" text,
	"actions" text NOT NULL,
	"multiattack" text,
	"bonusActions" text,
	"reactions" text,
	"specialActions" text,
	"sizeAndSpace" text NOT NULL,
	"sizeCategory" text,
	"reach" text,
	"spaceOccupied" text,
	"alignmentAndPersonality" text NOT NULL,
	"alignment" text,
	"ideals" text,
	"bonds" text,
	"flaws" text,
	"personalityTraits" text,
	"languages" text NOT NULL,
	"miscellaneousStats" text NOT NULL,
	"challengeRating" text,
	"experiencePoints" text,
	"toolProficiencies" text,
	"equipment" text,
	"factionsOrAffiliations" text,
	CONSTRAINT "entity_id_unique" UNIQUE("id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "playerCharacter" (
	"id" text PRIMARY KEY NOT NULL,
	"project" text NOT NULL,
	"name" text NOT NULL,
	"description" text NOT NULL,
	"playerClass" text NOT NULL,
	"level" text NOT NULL,
	"background" text NOT NULL,
	"entity" text NOT NULL,
	CONSTRAINT "playerCharacter_id_unique" UNIQUE("id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "projects" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text NOT NULL,
	"notes" text,
	"documents" text,
	CONSTRAINT "projects_id_unique" UNIQUE("id")
);
