CREATE TABLE IF NOT EXISTS "monsters" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"size" text NOT NULL,
	"type" text NOT NULL,
	"alignment" text NOT NULL,
	"armour_class" text NOT NULL,
	"armour_class_type" text NOT NULL,
	"hit_points" text NOT NULL,
	"hit_points_calculation" text NOT NULL,
	"speed" text NOT NULL,
	"stats" text NOT NULL,
	"saving_throws" text,
	"skills" text,
	"immunities_resistances" text NOT NULL,
	"senses" text NOT NULL,
	"passive_perception" text,
	"languages" text NOT NULL,
	"challenge_rating" text NOT NULL,
	"experience" text NOT NULL,
	"traits" text NOT NULL,
	"actions" text NOT NULL,
	"reactions" text,
	"legendary_actions" text,
	CONSTRAINT "monsters_id_unique" UNIQUE("id")
);
